### PR TITLE
Add rancher_secret resource type

### PR DESCRIPTION
**Pull request by raphink**

### CODE REVIEW

**Comment by cloudnautique** [comment]
Docs coming?

**Comment by raphink** [comment]
Yes, docs coming @cloudnautique. Although for now, I'm stuck with this: https://forums.rancher.com/t/updating-service-secret/6739

**Comment by raphink** [comment]
Actually, it works fine using a reference, e.g.

```hcl
resource rancher_secret "foo" {
  name           = "bar"
  description    = "my secret"
  environment_id = "1a124547"
  value = "hello world\n"
}

resource rancher_stack "test" {
  name = "test"
  environment_id = "1a124547"
  start_on_create = true
  finish_upgrade = true

  docker_compose = <<EOF
version: '2'
services:
  test:
    image: "ubuntu"
    command: "/sbin/init"
    secrets:
    - "${rancher_secret.foo.name}"
EOF
}
```

Whenever the secret value is changed, the resource is recreated, and the stack is upgraded, thus updating the secret.

**Comment by raphink** [comment]
@cloudnautique added the doc

**Pull request merged**
